########################
# INTEGRATION PROFILE
########################
spring.config.import=optional:file:.env[.properties]

########################
# DATABASE
########################
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_integration_test
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

########################
# ACTUATOR & METRICS
########################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

########################
# JWT
########################
jwt.secret=${JWT_HASH}
jwt.expiration=86400000

spring.jackson.time-zone=GMT+5
spring.jackson.date-format=yyyy-MM-dd

########################
# EUREKA
########################
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false

########################
# MESSAGING — real ActiveMQ
########################
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

workload.queue.name=trainer.workload.queue
