spring.application.name=gym-crm-lab-project

spring.profiles.active=local

########################
# METRICS CONFIGURATION
########################
gym.metrics.auth.success=gym.auth.success.total
gym.metrics.auth.failure=gym.auth.failure.total

gym.metrics.trainee.timer=gym.trainee.creation.time
gym.metrics.trainer.timer=gym.trainer.creation.time
gym.metrics.training.timer=gym.training.creation.time

