########################
# DOCKER PROFILE
########################

########################
# DATABASE
########################
spring.datasource.url=jdbc:h2:mem:gymdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:docker-seed-data.sql

spring.jpa.show-sql=false

########################
# EUREKA
########################
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false

########################
# ACTIVEMQ
########################
spring.activemq.broker-url=vm://embedded?broker.persistent=false&broker.useJmx=false
spring.jms.cache.enabled=false
workload.queue.name=trainer.workload.queue

########################
# JWT
########################
jwt.secret=${JWT_HASH}
jwt.expiration=86400000

########################
# JACKSON
########################
spring.jackson.time-zone=GMT+5
spring.jackson.date-format=yyyy-MM-dd

########################
# METRICS
########################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=false
