########################
# DOCKER COMPOSE PROFILE
########################

########################
# DATABASE
########################
spring.datasource.url=jdbc:postgresql://postgres:5432/gym_crm_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

########################
# EUREKA
########################
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false

########################
# ACTIVEMQ
########################
spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}
workload.queue.name=trainer.workload.queue

########################
# JWT
########################
jwt.secret=${JWT_HASH}
jwt.expiration=86400000

########################
# JACKSON
########################
spring.jackson.time-zone=GMT+5
spring.jackson.date-format=yyyy-MM-dd

########################
# METRICS
########################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

########################
# LOGGING
########################
logging.pattern.console=[%X{transactionId}] %d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
