spring.application.name=spring-core-task-1

storage.trainer.path=src/main/resources/data/trainers.csv
storage.trainee.path=src/main/resources/data/trainees.csv
storage.training.path=src/main/resources/data/trainings.csv
