########################
# LOCAL ENVIRONMENT
########################
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

########################
# ACTUATOR & METRICS
########################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

########################
# JWT
########################
jwt.secret=d1R4y47Ik8oxC/2wqJOHRmdRHz7R4hZS+kwJ2j9UaVNTKESBkAgQETLG+xuTgiePspUstVHjosV2E7MErkXQHDjWMQouhlzcre2YrZvwGclZUwWxFjYHSR73PGGJ4ZM+dQkp+Ja0K/HyrnJfLwJ715QEOnXqu2UAP6/73hNKOpK2MaJqxAZcm3PRsfQIv0KpeuNYo/9moFJk6n0uJPH+KJa9RGE68Ac8BKficxIRo8l/v1A4PKXrIVl9dlgEgXf7c7+0Q/ut8Hbbg4lR+IXOyuJFF7Ai3lwtScVz9LRrdIsjrwXXuzr/zixRP44vXyNIqCuWNWmmr7HGZwhlOZetg==
jwt.expiration=86400000
