########################
# LOCAL ENVIRONMENT
########################
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

########################
# ACTUATOR & METRICS
########################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

########################
# JWT
########################
jwt.secret=${JWT_HASH}
jwt.expiration=86400000

spring.jackson.time-zone=GMT+5
spring.jackson.date-format=yyyy-MM-dd

########################
# EUREKA CLIENT
########################
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

########################
# FEIGN + CIRCUIT BREAKER
########################
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.group.enabled=true

spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true

########################
# RESILIENCE4J
########################
resilience4j.circuitbreaker.configs.default.sliding-window-size=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.register-health-indicator=true

resilience4j.circuitbreaker.instances.gym-trainer-workload.base-config=default

logging.pattern.console=[%X{transactionId}] %d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
